// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1kEWAacMOc90XM13E5GbvFBN2ekT7sCI',
    appId: '1:401996080344:web:b25d3704b365baec0de3ad',
    messagingSenderId: '401996080344',
    projectId: 'real-estate-new-7ff3e',
    authDomain: 'real-estate-new-7ff3e.firebaseapp.com',
    storageBucket: 'real-estate-new-7ff3e.firebasestorage.app',
    measurementId: 'G-F9QZ5FF6LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlr6B4TYPlLngF_Vg_J8-bgo6W6EzsW2A',
    appId: '1:401996080344:android:2a00758a904e9fc90de3ad',
    messagingSenderId: '401996080344',
    projectId: 'real-estate-new-7ff3e',
    storageBucket: 'real-estate-new-7ff3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHaYHagFOXyTdXF97xhVmenvl26588XI',
    appId: '1:401996080344:ios:f9900a46a7d6872e0de3ad',
    messagingSenderId: '401996080344',
    projectId: 'real-estate-new-7ff3e',
    storageBucket: 'real-estate-new-7ff3e.firebasestorage.app',
    iosBundleId: 'com.example.krobarHub',
  );
}
